#request fields
geometry_msgs/PoseStamped start_pose #start pose for the planner
geometry_msgs/PoseStamped goal_pose #start pose for the planner
---
# True on success, false on planning failure
bool success
# Either contains a polynomial trajectory:
trajectory_msgs/MultiDOFJointTrajectory sampled_plan
